### ISSUE TITLE
could not find version on windows

### ISSUE THREAD

**Issue by ranasikandar** [akshaypai/tfClassifier#1]
i already have installed python 3.5

![capture](https://cloud.githubusercontent.com/assets/14071666/26632594/0e214bcc-462a-11e7-8954-c7abc7ce4601.PNG)
![capture1](https://cloud.githubusercontent.com/assets/14071666/26632600/129dd184-462a-11e7-8a61-8bbfc7117286.PNG)

**Comment by sourcedexter** [comment]
You have to install the dependencies to make this work. 
 To install numpy, follow the procedure given in the answers; https://stackoverflow.com/questions/11200137/installing-numpy-on-64bit-windows-7-with-python-2-7-3 
in case you get such errors again saying "module not found", it usually means that the module is not installed. A quick search on "how to install <module name> on Windows" will give you the procedure to do so.
