### ISSUE TITLE
Plot the hidden layer output of image classifier?

### ISSUE THREAD

**Issue by ChenSiLiang** [akshaypai/tfClassifier#12]
Hi, I'm retraining the image classifier model and I want to plot the output of each hidden layer to check the interesting feature. How can I do that? 
Thanks!

**Comment by sourcedexter** [comment]
Hi,

I haven't done that yet. So, I'm not sure how exactly it cane be done and
what kind of processing you'd need to make sense out of it.

Anyway, found an article on medium, you can have a look if it helps you
: “Visualizing Neural Network Layer Activation (Tensorflow Tutorial)” by
Arthur Juliani https://link.medium.com/OjMRnyhITV

**Comment by ChenSiLiang** [comment]
Thanks man!
