### ISSUE TITLE
Version incompatibilities

### ISSUE THREAD

**Issue by mrunmayeekulkarni** [akshaypai/tfClassifier#17]
Can you please tell me the versions used.. 
I am facing many incompatibilities
Using tensorflow version 1.13.1
can u guide with version of
tensorflow and tflearn

**Comment by sourcedexter** [comment]
Hi, this was built with Tensorlfoe 1.10 
with some small changes youshould be able to get it to run on 1.13 as well. the tf learn that i used was the one that comes with 1.10. hope this answers your query.

**Comment by mrunmayeekulkarni** [comment]
Yes..Thank you so much for your quick response.
Appreciated!
