### ISSUE TITLE
Costly algorithms are computationally  inefficient at all 

### ISSUE THREAD

**Issue by Nadedic** [akshaypai/tfClassifier#9]
Hello there, 

I admire your work and it took me some time to wrap my head around your [algorithm] (https://github.com/sourcedexter/tfClassifier/blob/master/text_classification/classify_text.py) 2nd loop to be particular.

The two nested loops I've found very costly, I haven't calculated the complexity but it seems that it might reach O(N^2) at times. I have 300k rows of data with text cells that represent "descriptions of certain categories" more than 50 words, so I am looking for approaches to manufacture a bag of words in a much smaller amount of time.

Thanks!

**Comment by Nadedic** [comment]
I mean, I used about 50 rows and it took me atleast 10 mins to train on 100 epochs. This code doesn't seem to be functional to real data at all sadly, or I must be doing something wrong.

**Comment by sourcedexter** [comment]
Hi Nadedic,  
I do agree that this method is not the most efficient one but I'm sure that it isn't as bad as what you have mentioned. I have done quite a bit of training and it usually takes not more than 15 seconds to train on 50 rows. And I train it for 1000 epochs.  I think there might some other issue like hardware or some modifications that you might have made. As I do not have more details, I won't be able to help you with how to improve.

**Comment by Nadedic** [comment]
Ok, let me explain my data better. I'm importing from a local database server say 50 rows considering the important text part would have something like: 

"I cannot view technical drawings when I log into teamcenter the browser freezes I also need java updated and teamcenter viewer installed to view the drawings  I also cannot run the software ***** **** ****** ************ **** **** ***** ************* ****** ********* ******* ***** **** ***** as it pops up a message to select a printer when I do select a printer the error as per attached image appears. "

Consider each * as a character, this is easily more than 100 character for example. One row could range till 500 characters for example. I think that is I think it could reach 10000 words appending and stemming all this data within the nested loops seems very costly.  

I've followed your way all the way, only difference is how I import and export data. Using a database connection, formed two lists from a dataframe and that's it.

I am honestly considering my CPU, I have tensorflow with no GPU extension but that would not affect the upper loops before the training section. I am going to share my CPU also just incase it might be a huge factor: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz, 2400 Mhz, 2 Core(s), 4 Logical Processor(s) and 8 gigs of ram.

**Comment by sourcedexter** [comment]
were you able to solve this issue? 
To give you some context, I used to run image processing with neural networks, and there is a topic called transfer style. I used run transfer style with a run time of 5 to 6 hours for 1 image on CPU. 
But on a GPU, that came down to 15 minutes.

So, using a GPU might significantly improve the performance.

**Comment by sourcedexter** [comment]
Closing the issue for now, but if you still have any question, please do re-open
